shell = "/usr/bin/zsh"

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "JetBrains Mono NF"
bold.family = "JetBrains Mono NF"
italic.family = "JetBrains Mono NF"
bold_italic.family = "JetBrains Mono NF"

size = 16.0
